/armor_finder:
  ros__parameters:
    enemy_color: "red"
    model_path: "./res/armor_numbers.xml"

/frame_capture:
  ros__parameters:
    vid_path: "./res/pic/red_test.png"
    playing: false
    loop_display: false